import Head from "next/head";
import { ReactNode } from "react";
import Card from "./Card";

const Layout = ({
  children,
  className,
}: {
  children?: ReactNode;
  className?: string;
}) => {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Card className={className}>{children}</Card>
      </main>
    </>
  );
};

export default Layout;
